In [1]:
# question6- Write a logistic regression program for predicting customer will subscribe for term
# deposit Refer Bank data set 2

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report

data = pd.read_excel("C:/Users/Pranav/ML DL practical/Datasets/Bank data set 2.xlsx")

In [2]:
data

    Duration  Subscription
0         171           no
1         840          yes
2         206           no
3         747          yes
4         263           no
5         331          yes
6         334           no
7         268           no
8         208          yes
9         268          yes
10        346           no
11        363          yes
12        113           no
13        173           no
14         68           no
15        539          yes
16         35           no
17        119           no
18        728          yes
19        412          yes
20        314           no
21         99           no
22         25           no
23        252          yes
24       1348          yes
25        314           no
26        955          yes
27        224          yes
28        406           no
29        205          yes
30        266          yes
31        153           no
32        195          yes
33        316          yes
34        768          yes
35        300          yes
36        483          yes
37        391           no
38        276          yes
39        275           no
40        175           no
41        126           no
42        101           no
43        653          yes
44        286          yes
45        650          yes
46        450          yes
47        239           no
48        125           no
49       1855          yes
50        128           no

In [3]:
X = data[['Duration']]
y = data['Subscription']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the data (optional but recommended for logistic regression)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

KeyError: "None of [Index(['Duration'], dtype='object')] are in the [columns]"